version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:15.11.0
    steps:
      - checkout
      - run:
          name: Install python
          command: sudo apt-get update && sudo apt-get install python -y
      - run: 
          name: Install dependencies
          command: yarn install
      - run: 
          name: Build website
          command: yarn build
      - run:
          name: Configure git
          command: git config --global user.email "imccausl@gmail.com" && git config --global user.name "CircleCI Deploy"
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  version: 2
  build:
    jobs:
      - build-and-deploy