version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:15.11.0
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: yarn install
      - run: 
          name: Build website
          command: yarn build
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  version: 2
  build:
    jobs:
      - build-and-deploy